const EXTENSION_CONTENT_TYPES: Readonly<Record<string, string>> = {
  '3g2': 'video/3gpp2',
  '3gp': 'video/3gpp',
  '7z': 'application/x-7z-compressed',
  aac: 'audio/aac',
  apng: 'image/apng',
  avif: 'image/avif',
  avi: 'video/x-msvideo',
  bat: 'application/x-bat',
  bmp: 'image/bmp',
  bz2: 'application/x-bzip2',
  c: 'text/x-c',
  cc: 'text/x-c++src',
  conf: 'text/plain',
  cpp: 'text/x-c++src',
  css: 'text/css',
  csv: 'text/csv',
  cxx: 'text/x-c++src',
  dart: 'text/x-dart',
  dmg: 'application/x-apple-diskimage',
  doc: 'application/msword',
  docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  env: 'text/plain',
  eot: 'application/vnd.ms-fontobject',
  epub: 'application/epub+zip',
  flac: 'audio/flac',
  gif: 'image/gif',
  go: 'text/x-go',
  gz: 'application/gzip',
  h: 'text/x-c-header',
  heic: 'image/heic',
  heif: 'image/heif',
  hpp: 'text/x-c++hdr',
  htm: 'text/html',
  html: 'text/html',
  ico: 'image/x-icon',
  ini: 'text/plain',
  java: 'text/x-java-source',
  jpeg: 'image/jpeg',
  jpg: 'image/jpeg',
  js: 'text/javascript',
  json: 'application/json',
  jsx: 'text/jsx',
  kt: 'text/x-kotlin',
  kts: 'text/x-kotlin',
  log: 'text/plain',
  lua: 'text/x-lua',
  m4a: 'audio/mp4',
  m4v: 'video/x-m4v',
  md: 'text/markdown',
  mdx: 'text/mdx',
  mkv: 'video/x-matroska',
  mov: 'video/quicktime',
  mp3: 'audio/mpeg',
  mp4: 'video/mp4',
  mpeg: 'video/mpeg',
  mpg: 'video/mpeg',
  odp: 'application/vnd.oasis.opendocument.presentation',
  ods: 'application/vnd.oasis.opendocument.spreadsheet',
  odt: 'application/vnd.oasis.opendocument.text',
  ogg: 'audio/ogg',
  opus: 'audio/opus',
  otf: 'font/otf',
  pdf: 'application/pdf',
  php: 'application/x-httpd-php',
  png: 'image/png',
  ppt: 'application/vnd.ms-powerpoint',
  pptx: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  ps: 'application/postscript',
  psd: 'image/vnd.adobe.photoshop',
  py: 'text/x-python',
  rar: 'application/vnd.rar',
  rs: 'text/x-rust',
  rtf: 'application/rtf',
  scss: 'text/x-scss',
  sh: 'application/x-sh',
  sql: 'application/sql',
  svg: 'image/svg+xml',
  svelte: 'text/x-svelte',
  swift: 'text/x-swift',
  tar: 'application/x-tar',
  tif: 'image/tiff',
  tiff: 'image/tiff',
  toml: 'application/toml',
  ts: 'text/x-typescript',
  tsv: 'text/tab-separated-values',
  tsx: 'text/x-typescript',
  ttf: 'font/ttf',
  txt: 'text/plain',
  vue: 'text/x-vue',
  wav: 'audio/wav',
  webm: 'video/webm',
  webp: 'image/webp',
  woff: 'font/woff',
  woff2: 'font/woff2',
  xls: 'application/vnd.ms-excel',
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  xml: 'application/xml',
  xz: 'application/x-xz',
  yaml: 'text/yaml',
  yml: 'text/yaml',
  zip: 'application/zip',
  zst: 'application/zstd',
}

export function getFileExtension(fileName: string) {
  const baseName = fileName.split(/[\\/]/).pop() ?? fileName
  const dotIndex = baseName.lastIndexOf('.')

  return dotIndex < 0 ? '' : baseName.slice(dotIndex + 1).toLowerCase()
}

export function inferFileContentType(fileName: string) {
  return EXTENSION_CONTENT_TYPES[getFileExtension(fileName)]
}
