export type AgentProviderCategory = 'api_key' | 'cloud' | 'subscription'

export type AgentProviderAuthConfig = {
  category: AgentProviderCategory
  envVarNames: string[]
  groupCategories?: AgentProviderCategory[]
  label: string
  placeholder?: string
  provider: string
  setupHint?: string
  supportsApiKey: boolean
  supportsOAuth: boolean
}

export const AGENT_PROVIDER_AUTH_CONFIGS: AgentProviderAuthConfig[] = [
  {
    category: 'subscription',
    envVarNames: [],
    label: 'ChatGPT Plus/Pro (Codex)',
    provider: 'openai-codex',
    setupHint: '需要 ChatGPT Plus 或 Pro 订阅。',
    supportsApiKey: false,
    supportsOAuth: true,
  },
  {
    category: 'subscription',
    envVarNames: ['ANTHROPIC_OAUTH_TOKEN', 'ANTHROPIC_API_KEY'],
    groupCategories: ['subscription', 'api_key'],
    label: 'Claude Pro/Max / Anthropic',
    placeholder: 'sk-ant-...',
    provider: 'anthropic',
    setupHint: '订阅登录会走 Claude extra usage，按 token 计费。',
    supportsApiKey: true,
    supportsOAuth: true,
  },
  {
    category: 'subscription',
    envVarNames: ['COPILOT_GITHUB_TOKEN'],
    label: 'GitHub Copilot',
    provider: 'github-copilot',
    setupHint: 'GitHub Enterprise 域名留空时使用 github.com。',
    supportsApiKey: false,
    supportsOAuth: true,
  },
  {
    category: 'api_key',
    envVarNames: ['OPENROUTER_API_KEY'],
    label: 'OpenRouter',
    placeholder: 'sk-or-v1-...',
    provider: 'openrouter',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'api_key',
    envVarNames: ['OPENAI_API_KEY'],
    label: 'OpenAI',
    placeholder: 'sk-...',
    provider: 'openai',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'api_key',
    envVarNames: ['GEMINI_API_KEY'],
    label: 'Google Gemini',
    placeholder: 'API key',
    provider: 'google',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'api_key',
    envVarNames: ['DEEPSEEK_API_KEY'],
    label: 'DeepSeek',
    placeholder: 'sk-...',
    provider: 'deepseek',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'api_key',
    envVarNames: ['MISTRAL_API_KEY'],
    label: 'Mistral',
    placeholder: 'API key',
    provider: 'mistral',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'api_key',
    envVarNames: ['GROQ_API_KEY'],
    label: 'Groq',
    placeholder: 'gsk_...',
    provider: 'groq',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'api_key',
    envVarNames: ['CEREBRAS_API_KEY'],
    label: 'Cerebras',
    placeholder: 'API key',
    provider: 'cerebras',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'api_key',
    envVarNames: ['XAI_API_KEY'],
    label: 'xAI',
    placeholder: 'xai-...',
    provider: 'xai',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'api_key',
    envVarNames: ['AI_GATEWAY_API_KEY'],
    label: 'Vercel AI Gateway',
    placeholder: 'vck_...',
    provider: 'vercel-ai-gateway',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'api_key',
    envVarNames: ['ZAI_API_KEY'],
    label: 'ZAI',
    placeholder: 'API key',
    provider: 'zai',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'api_key',
    envVarNames: ['OPENCODE_API_KEY'],
    label: 'OpenCode Zen',
    placeholder: 'API key',
    provider: 'opencode',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'api_key',
    envVarNames: ['OPENCODE_API_KEY'],
    label: 'OpenCode Go',
    placeholder: 'API key',
    provider: 'opencode-go',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'api_key',
    envVarNames: ['HF_TOKEN'],
    label: 'Hugging Face',
    placeholder: 'hf_...',
    provider: 'huggingface',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'api_key',
    envVarNames: ['FIREWORKS_API_KEY'],
    label: 'Fireworks',
    placeholder: 'fw_...',
    provider: 'fireworks',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'api_key',
    envVarNames: ['TOGETHER_API_KEY'],
    label: 'Together AI',
    placeholder: 'API key',
    provider: 'together',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'api_key',
    envVarNames: ['KIMI_API_KEY'],
    label: 'Kimi For Coding',
    placeholder: 'API key',
    provider: 'kimi-coding',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'api_key',
    envVarNames: ['MINIMAX_API_KEY'],
    label: 'MiniMax',
    placeholder: 'API key',
    provider: 'minimax',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'api_key',
    envVarNames: ['MINIMAX_CN_API_KEY'],
    label: 'MiniMax (China)',
    placeholder: 'API key',
    provider: 'minimax-cn',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'api_key',
    envVarNames: ['MOONSHOT_API_KEY'],
    label: 'Moonshot AI',
    placeholder: 'API key',
    provider: 'moonshotai',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'api_key',
    envVarNames: ['MOONSHOT_API_KEY'],
    label: 'Moonshot AI (China)',
    placeholder: 'API key',
    provider: 'moonshotai-cn',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'api_key',
    envVarNames: ['XIAOMI_API_KEY'],
    label: 'Xiaomi MiMo',
    placeholder: 'API key',
    provider: 'xiaomi',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'api_key',
    envVarNames: ['XIAOMI_TOKEN_PLAN_CN_API_KEY'],
    label: 'Xiaomi MiMo Token Plan (China)',
    placeholder: 'API key',
    provider: 'xiaomi-token-plan-cn',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'api_key',
    envVarNames: ['XIAOMI_TOKEN_PLAN_AMS_API_KEY'],
    label: 'Xiaomi MiMo Token Plan (Amsterdam)',
    placeholder: 'API key',
    provider: 'xiaomi-token-plan-ams',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'api_key',
    envVarNames: ['XIAOMI_TOKEN_PLAN_SGP_API_KEY'],
    label: 'Xiaomi MiMo Token Plan (Singapore)',
    placeholder: 'API key',
    provider: 'xiaomi-token-plan-sgp',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'cloud',
    envVarNames: ['AZURE_OPENAI_API_KEY'],
    label: 'Azure OpenAI Responses',
    placeholder: 'API key',
    provider: 'azure-openai-responses',
    setupHint: '还需要 AZURE_OPENAI_BASE_URL 或 AZURE_OPENAI_RESOURCE_NAME。',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'cloud',
    envVarNames: ['CLOUDFLARE_API_KEY'],
    label: 'Cloudflare AI Gateway',
    placeholder: 'API token',
    provider: 'cloudflare-ai-gateway',
    setupHint: '还需要 CLOUDFLARE_ACCOUNT_ID 和 CLOUDFLARE_GATEWAY_ID。',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'cloud',
    envVarNames: ['CLOUDFLARE_API_KEY'],
    label: 'Cloudflare Workers AI',
    placeholder: 'API token',
    provider: 'cloudflare-workers-ai',
    setupHint: '还需要 CLOUDFLARE_ACCOUNT_ID。',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'cloud',
    envVarNames: [
      'GOOGLE_CLOUD_API_KEY',
      'GOOGLE_APPLICATION_CREDENTIALS',
      'GOOGLE_CLOUD_PROJECT',
      'GCLOUD_PROJECT',
      'GOOGLE_CLOUD_LOCATION',
    ],
    label: 'Google Vertex AI',
    placeholder: 'API key',
    provider: 'google-vertex',
    setupHint: '推荐使用 ADC：gcloud auth application-default login，并设置 project/location；GOOGLE_CLOUD_API_KEY 也可作为显式 key。',
    supportsApiKey: true,
    supportsOAuth: false,
  },
  {
    category: 'cloud',
    envVarNames: [
      'AWS_PROFILE',
      'AWS_ACCESS_KEY_ID',
      'AWS_SECRET_ACCESS_KEY',
      'AWS_BEARER_TOKEN_BEDROCK',
      'AWS_CONTAINER_CREDENTIALS_RELATIVE_URI',
      'AWS_CONTAINER_CREDENTIALS_FULL_URI',
      'AWS_WEB_IDENTITY_TOKEN_FILE',
    ],
    label: 'Amazon Bedrock',
    provider: 'amazon-bedrock',
    setupHint: '使用 AWS profile、IAM keys、Bedrock bearer token、ECS 凭据或 IRSA。',
    supportsApiKey: false,
    supportsOAuth: false,
  },
]

export const AGENT_PROVIDER_AUTH_CONFIG_BY_ID = new Map(
  AGENT_PROVIDER_AUTH_CONFIGS.map((config) => [config.provider, config]),
)

export function getAgentProviderAuthConfig(provider: string): AgentProviderAuthConfig {
  return AGENT_PROVIDER_AUTH_CONFIG_BY_ID.get(provider) ?? {
    category: 'api_key',
    envVarNames: [],
    label: provider,
    placeholder: 'API key',
    provider,
    supportsApiKey: true,
    supportsOAuth: false,
  }
}

export function getAgentProviderOrder(provider: string) {
  const index = AGENT_PROVIDER_AUTH_CONFIGS.findIndex((config) => config.provider === provider)
  return index >= 0 ? index : AGENT_PROVIDER_AUTH_CONFIGS.length
}
