export const VIEWER_COPY = {
  clear: "清除",
  comments: "批注",
  currentPageEdit: "编辑当前页码",
  darkMode: "深色模式",
  download: "下载",
  docxDownloadFailed: "DOCX 文件下载失败。",
  docxFetchFailed: "DOCX 文件加载失败。",
  docxUnsupportedFile: "仅支持 .docx 文件。",
  fileTooLarge: "文件过大",
  nextResult: "下一个结果",
  noResults: "无结果",
  noSearch: "未搜索",
  nextPage: "下一页",
  openCsvActions: "打开 CSV 操作菜单",
  openDocxActions: "打开 DOCX 操作菜单",
  openPdfActions: "打开 PDF 操作菜单",
  openWorkbookActions: "打开工作簿操作菜单",
  page: "页",
  pageNumber: "页码",
  previousPage: "上一页",
  previousResult: "上一个结果",
  rotateClockwise: "顺时针旋转",
  rotateCounterclockwise: "逆时针旋转",
  searchCsv: "搜索 CSV",
  searchText: "搜索文本",
  searchWorkbook: "搜索工作簿",
  searching: "搜索中",
  showComments: "显示批注",
  showTrackedChanges: "显示修订",
  sortAscending: "升序排序",
  sortDescending: "降序排序",
  toggleThumbnails: "显示或隐藏缩略图",
  trackedChanges: "修订",
  unableToDisplayWorkbook: "无法显示工作簿。",
  unableToLoadDocx: "DOCX 文件加载失败。",
  unableToLoadPdfEngine: "无法加载 PDF 引擎。",
  unableToLoadPdfPreview: "无法加载 PDF 预览。",
  unableToParseCsv: "无法解析 CSV 文件。",
  pdfDownloadFailed: "PDF 文件下载失败。",
  upload: "上传",
  uploadCsv: "上传 CSV",
  uploadCsvHelp: "传入分隔文本，或上传本地 CSV 文件。",
  uploadCsvToPreview: "上传 CSV 以预览",
  uploadDocx: "上传 DOCX",
  uploadDocxHelp: "传入 DOCX 文件地址，或上传本地 DOCX 文件。",
  uploadDocxToPreview: "上传 DOCX 以预览",
  uploadPdfHelp: "传入 PDF 文件地址，或上传本地 PDF 文件。",
  uploadPdfToPreview: "上传 PDF 以预览",
  uploadWorkbookHelp: "传入工作簿文件地址，或上传本地 XLSX 文件。",
  uploadWorkbookToPreview: "上传工作簿以预览",
  uploadXlsx: "上传 XLSX",
  workbookLoadFailed: "工作簿加载失败。",
  workbookTooLargeHelp: "此工作簿超过显示限制，请下载后查看完整文件。",
  zoomIn: "放大",
  zoomLevel: "缩放比例",
  zoomOut: "缩小",
} as const;

export const DOCX_ANNOTATION_COPY = {
  comment: "批注",
  inserted: "已插入",
  movedFrom: "移自",
  movedTo: "移至",
  removed: "已删除",
  reply: "回复",
  resolved: "已解决",
  unknownAuthor: "未知作者",
} as const;
